name: Ohio InfoSec Forum
subtitle: Networking, sharing, collaborating, learning... helping secure our digital world.
author: OISF
email: info@ohioinfosec.org
description: Networking, sharing, collaborating, learning... helping secure our digital world.
url: http://www.ohioinfosec.org
date_format: "ordinal"
timezone: America/Detroit
markdown: redcarpet
highlighter: rouge
category_dir: /blog/categories
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "blog/page/:num/"
exclude: [/Gemfile, /Gemfile.lock, /Rakefile, /README.md, LICENSE, .gitignore]
gems: ["jekyll-paginate"]
